// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the token.properties.
#include "../../../../../SiliconLabs/SimplicityStudio/v4_2/developer/sdks/gecko_sdk_suite/v2.7/protocol/zigbee/app/framework/util/tokens.h"

// Token header for the Manufacturing Library CLI plugin.
#include "../../../../../SiliconLabs/SimplicityStudio/v4_2/developer/sdks/gecko_sdk_suite/v2.7/protocol/zigbee/app/framework/plugin/manufacturing-library-cli/manufacturing-library-cli-tokens.h"

// Token header for the Connection Manager plugin.
#include "../../../../../SiliconLabs/SimplicityStudio/v4_2/developer/sdks/gecko_sdk_suite/v2.7/protocol/zigbee/app/framework/plugin-soc/connection-manager/connection-manager-tokens.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

